# Numpy Assignment

# Question No.1:

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of `N - i - 1.`

HINT: Such a matrix with a geometric progression in each row is named for `Alexandre- Theophile Vandermonde.`

In [1]:
import numpy as np

In [2]:
def make_vander(inputvector, n, increasing =False):
    inputvector = np.array(inputvector)
    if not increasing:
        vandermatrix = np.array([x**(n-1-i) for x in inputvector for i in range(n)])
        vandermatrix = vandermatrix.reshape(inputvector.size,n)
    else:
        vandermatrix = np.array([ x**i for x in inputvector for i in range(n)])
        vandermatrix = vandermatrix.reshape(inputvector.size,n)
    return vandermatrix

In [3]:
make_vander([1,2,3,4],5,False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [4]:
np.vander([1,2,3,4],5,False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [5]:
make_vander([1,2,3,4],5,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256]])

In [6]:
np.vander([1,2,3,4],5,True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256]])

# Question No.2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
>1.The moving average sequence has n-k+1 elements as shown below.

>2.The moving averages with k=4 of a ten-value sequence (n=10) is shown below

Write a function to find moving average in an array over a window: 

Test it over `[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]` 
and `window of 3.`

In [7]:
test = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [8]:
k = 3

# Using For Loop

In [9]:
moving_average = []
for i in range(len(test)-k+1):
    c=0
    for j in range(k):
        c=c+test[j+i]
    c=c//k
    moving_average.append(c)

In [10]:
moving_average

[5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]

# Using Numpy Cumsum Function to Subtract the Window Size Values

In [11]:
csum = np.cumsum(test)
csum

array([  3,   8,  15,  17,  25,  35,  46, 111, 183, 264, 363, 463, 613],
      dtype=int32)

This Below Code Will Subtract The given Window Value Gap

In [12]:
csum[k:]-=csum[:-k]
csum

array([  3,   8,  15,  14,  17,  20,  29,  86, 148, 218, 252, 280, 349],
      dtype=int32)

In [13]:
result=csum[k-1:]//k

In [14]:
result

array([  5,   4,   5,   6,   9,  28,  49,  72,  84,  93, 116], dtype=int32)